/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the kisiler service. Represents a row in the &quot;kisi_bilgileri&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.kisilerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.kisilerImpl}.
 * </p>
 *
 * @author giray
 * @see kisiler
 * @see com.liferay.sample.model.impl.kisilerImpl
 * @see com.liferay.sample.model.impl.kisilerModelImpl
 * @generated
 */
public interface kisilerModel extends BaseModel<kisiler> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a kisiler model instance should use the {@link kisiler} interface instead.
	 */

	/**
	 * Returns the primary key of this kisiler.
	 *
	 * @return the primary key of this kisiler
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this kisiler.
	 *
	 * @param primaryKey the primary key of this kisiler
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the kid of this kisiler.
	 *
	 * @return the kid of this kisiler
	 */
	public int getKid();

	/**
	 * Sets the kid of this kisiler.
	 *
	 * @param kid the kid of this kisiler
	 */
	public void setKid(int kid);

	/**
	 * Returns the name of this kisiler.
	 *
	 * @return the name of this kisiler
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this kisiler.
	 *
	 * @param name the name of this kisiler
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(kisiler kisiler);

	@Override
	public int hashCode();

	@Override
	public CacheModel<kisiler> toCacheModel();

	@Override
	public kisiler toEscapedModel();

	@Override
	public kisiler toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}